apiVersion: 0.3.0
environments:
  default:
    destination:
      namespace: kubeflow
      server: https://A7BACDA5C7DBF0FBC76C18DF0CC83477.sk1.us-east-1.eks.amazonaws.com
    k8sVersion: v1.10.11
    path: default
kind: ksonnet.io/app
libraries:
  kubeflow/application:
    name: application
    registry: kubeflow
    version: ""
  kubeflow/argo:
    name: argo
    registry: kubeflow
    version: ""
  kubeflow/core:
    name: core
    registry: kubeflow
    version: ""
  kubeflow/examples:
    name: examples
    registry: kubeflow
    version: ""
  kubeflow/jupyter:
    name: jupyter
    registry: kubeflow
    version: ""
  kubeflow/katib:
    name: katib
    registry: kubeflow
    version: ""
  kubeflow/metacontroller:
    name: metacontroller
    registry: kubeflow
    version: ""
  kubeflow/modeldb:
    name: modeldb
    registry: kubeflow
    version: ""
  kubeflow/mpi-job:
    name: mpi-job
    registry: kubeflow
    version: ""
  kubeflow/openmpi:
    name: openmpi
    registry: kubeflow
    version: ""
  kubeflow/openvino:
    name: openvino
    registry: kubeflow
    version: ""
  kubeflow/pipeline:
    name: pipeline
    registry: kubeflow
    version: ""
  kubeflow/profiles:
    name: profiles
    registry: kubeflow
    version: ""
  kubeflow/pytorch-job:
    name: pytorch-job
    registry: kubeflow
    version: ""
  kubeflow/seldon:
    name: seldon
    registry: kubeflow
    version: ""
  kubeflow/tf-serving:
    name: tf-serving
    registry: kubeflow
    version: ""
  kubeflow/tf-training:
    name: tf-training
    registry: kubeflow
    version: ""
name: ks_app
registries:
  kubeflow:
    protocol: fs
    uri: /Users/pantelis/projects/devops/kf/kubeflow
version: 0.0.1
